##### HUGO Gene Nomenclature #######
hgnc_url: "ftp://ftp.ebi.ac.uk/pub/databases/genenames/new/tsv/hgnc_complete_set.txt"
mgi_url: "http://www.informatics.jax.org/downloads/reports/MGI_Gene_Model_Coord.rpt"
header:
  - "ID"
  - ":LABEL"
  - "name"
  - "family"
  - "entrez_id"
  - "ensembl_id"
  - "other_synonyms"
  - "taxid"
